# using triggers for every deployment and allowed manually
# docs on these triggers:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#deployment
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
name: Auto Approval

on: [deployment, workflow_dispatch]

jobs:
    auto_approve:
      runs-on: ubuntu-latest
      if: github.actor == 'approverauto' ##github bot for our case which is not the part of reviewer team 
      steps:
        - name: Auto Approve Deploys
          uses: activescott/automate-environment-deployment-approval@main
          with:
            github_token: ${{ secrets.WORKFLOW_APPROVAL }}
            environment_allow_list: |
              stg
              prd
            actor_allow_list: |
              RanjitThakur678
              approverauto

  